version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/certs
    depends_on:
      - api
    networks:
      - app-network
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - API_HOST=api

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
    entrypoint: sh -c "certbot certonly --standalone --preferred-challenges http --email ${EMAIL} --agree-tos --no-eff-email -d $DOMAIN_NAME && cp /etc/letsencrypt/live/$DOMAIN_NAME/fullchain.pem /certs && cp /etc/letsencrypt/live/$DOMAIN_NAME/privkey.pem /certs"
    depends_on:
      - nginx
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
