version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ~/certs:/certs
    depends_on:
      - api
    networks:
      - app-network
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - API_HOST=api

  api:
    build:
      context: .
      dockerfile: ../Dockerfile
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
