name: Release Interfaces to GitHub Packages

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build interfaces
        run: npm run build-interfaces

      - name: Publish to npm
        run: npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
