name: Label PR

on:
  pull_request:
    types: [opened]
    branches: [master, develop]
    
permissions:
  pull-requests: write


jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: actions/github-script@v5
        with:
          script: |
            const target = context.payload.pull_request.base.ref;
            let label = '';
            if (target === 'develop') {
              label = 'version/patch';
            } else if (target === 'master') {
              label = 'version/minor';
            }

            if (label) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [label]
              });
            }
          github-token: ${{secrets.GITHUB_TOKEN}}
