name: Version Bump
on:
  pull_request:
    types: [closed]
    branches: [master, develop]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # this is required for the action to be able to see tags

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Install dependencies
        run: sudo apt-get install jq

      - name: Analyze PR and determine version bump
        id: pr_analysis
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_INFO=$(curl -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer $GH_TOKEN"  -H "X-GitHub-Api-Version: 2022-11-28"   https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER)
          LABELS=$(jq --argjson data "$PR_INFO" '.labels[].name' <<< "$PR_INFO")
          if [[ "${{ github.event.pull_request.base.ref }}" == "master" ]] && echo "$LABELS" | grep -q "major"; then
            echo "::set-output name=version_bump::major"
          elif [[ "${{ github.event.pull_request.base.ref }}" == "master" ]]; then
            echo "::set-output name=version_bump::minor"
          else
            echo "::set-output name=version_bump::patch"
          fi
        env:
          GH_TOKEN: ${{ secrets.VERSION_BUMP_PAT }}


      - name: Bump version and push tag
        id: package
        run: |
          git config --local user.email "business.daniel.mass@gmail.com"
          git config --local user.name "Daniel Mass"
          gh auth login --with-token <<< '${{ secrets.VERSION_BUMP_PAT }}'
          gh auth status
          npm version ${{ steps.pr_analysis.outputs.version_bump }} -m "Upgrade to %s"
          git push
          git push --tags